### ISSUE TITLE
Lollipop 5.1 ARM64 - Nexus 9

### ISSUE THREAD

**Issue by kirschnerio** [mh0rst/skycast#10]
Thanks for the great work! I would love to see a custom Xposed version for Lollipop 5.1 ARM64 for my Nexus 9 LTE to be able to use Skycast. I already installed the ARM64 Xposed variant from romracer solely for Skycast and figured out, that your wunderfull piece of software needs a custom xposed version. ;-)

**Comment by mh0rst** [comment]
Hi there! Sorry to let you wait so long, I had to work on other stuff in the past few weeks.
Recent changes to Xposed enabled the needed modifications in the official builds, please check out https://github.com/mh0rst/skycast/wiki/skycast-on-Lollipop and follow the instructions for installation of Lollipop 5.1 on ARM64.
Please close this if it works for you :)
