### ISSUE TITLE
CM-12 Lollipop 5.02 Xposed & SkyCast

### ISSUE THREAD

**Issue by PanicBrothers** [mh0rst/skycast#4]
Moin,
ich lasse das mal hier auf deutsch :-)
Ich habe die oben erwähnte Softwarekombi auf meinem Z3 Compact Xperia am laufen. Das SkyCast Modul macht genau das was es soll und alle SkyGo Deutschland Inhalte werden auf dem Screen angezeigt.
Da Cyanogenmod12 als Nighlty noch kein USB MHL Output unterstützt, musste ich auf die Chromecast Funkverbindung zurückgreifen, leider funktioniert die Lollipop interne Bildschirmübertragung auch noch nicht (findet kein Device)
Nun ist die Bildqualität per Chromecast nicht so gut wie bei MHL auf HDMI Kabel und ab und an hackt das Bild.
Daher die Frage, kann das am XPosed Alpha Stadium liegen für Lollipop oder am SkyCast oder nur am WLan?
Oder Oder in jedem Fall möchte ich mich für das SkyCast schonmal bedanken, da ich jede Art von restriktionen in dieser Richtung ablehne. 
Danke Danke Danke

**Comment by mh0rst** [comment]
An XPosed oder SkyCast wird das nicht liegen, die haben mit der eigentlichen Bildübertragung nichts zu tun. Chromecast muss aufgrund der begrenzten Geschwindigkeit des WLANs den Bildschirminhalt transcodieren, daher die schlechtere Qualität. Die Ruckler würde ich noch am ehesten mit schwankender WLAN-Qualität erklären, das Z3 Compact müsste an sich schnell genug für das Transcodieren sein.
