### ISSUE TITLE
!!!HACK!!! in Sky Go App

### ISSUE THREAD

**Issue by chrisiari** [mh0rst/skycast#5]
Hi,
mit installiertem xposed und Skycast kommt direkt nach dem starten der Sky Go App ein Bildschirm, wo ganz groß !!!HACK!!! und ein Totenkopf steht! Gibts da schon irgendeine Abhilfe?
![screenshot_2015-04-05-03-26-37 1](https://cloud.githubusercontent.com/assets/11802346/6995372/e318ff90-db43-11e4-9c94-8a41d7a218e5.png)

**Comment by mh0rst** [comment]
Ja, auf meinem Rechner befindet sich bereits ein Fix. Ich muss nur noch etwas testen, dann gibts ein neues Release.

**Comment by mh0rst** [comment]
Wird von 4d50a9322e732f7fe3fa6242202c455376187a37 gefixt, Release baue ich morgen.

**Comment by srutster** [comment]
Problem besteht leider nach update auf 1.1 immer noch

**Comment by mh0rst** [comment]
Xposed unter Lollipop hat eine essentielle Funktion für das Modul noch nicht aktiviert, siehe #6. Da musst du leider Geduld haben oder auf 1.3.1 downgraden.
