### ISSUE TITLE
Lollipop?

### ISSUE THREAD

**Issue by fda77** [mh0rst/skycast#6]
Skull removal does not work with Lollipop due to Xposed limitation. In the log: "Not hooking native method ...doChecksAndLoad.
Maybe a more generic cloak-Xposed helps

**Comment by mh0rst** [comment]
Hi,
the only alternative to replacing the native method would be replacing all methods that call the native method, which would require copying large quantities of the original go app code.
This is undesirable, as it would involve unclean, disassembled code and probably infringe copyrights.
I'm afraid you will have to downgrade to version 1.3.1 or wait for an Xposed release that supports hooking native methods. Please watch http://goo.gl/JQF9MN on this topic.

**Comment by fda77** [comment]
Ah, da fällt mir ein es ist Sky Germany ist :)
Schreib doch in die Beschreibung dazu dass es nicht nur mit alten Android versionen kompatible ist

**Comment by mh0rst** [comment]
Guter Punkt. Ist nun im Xposed repo vermerkt, hier auf Github stand ja in der Readme schon immer, dass ich Lollipop noch nicht supporte :)

**Comment by fda77** [comment]
Jo, erspart installieren, ausprobieren und im Log stöbern

**Comment by mh0rst** [comment]
Wenn du magst, kannst du mal diese Version von Xposed testen: http://www19.zippyshare.com/v/WgsBBQSS/file.html
Sie entspricht der original 3.0 alpha2 von rovo89, hat aber den Ausstieg für native Methoden nicht aktiviert (https://github.com/rovo89/android_art/blob/xposed-lollipop/runtime/mirror/art_method.cc#L400).
Ich kann mangels Android 5 Gerät leider nicht testen, ob das funktioniert.

**Comment by fda77** [comment]
Cool, danke! Einfach die Abfrage deaktiviert oder sonst noch was geändert? Rovo hatte bestimmt seine Gründe das zu deaktivieren.
Btw, falls es nicht funktioniert/Bootloop oder so einfach die Version von Rovo drüber flashen?

**Comment by mh0rst** [comment]
Genau, ich habe die Abfrage auskommentiert. Die Begründung ist, dass es mehr Tests erfordert, um für alle aktiviert zu werden. Wie soll man aber ein Feature testen, wenn es überall deaktiviert ist ;)
Und ja, zum Zurückrollen einfach die Version von rovo wieder flashen.

**Comment by fda77** [comment]
@mh0rst: Sieht ganz gut aus auf Nexus 7 5.0.2! Die App ist nutzbar

```
04-10 21:47:42.086: I/Xposed(13559): [SkyCast] MediaRouter hooked
04-10 21:47:42.129: I/Xposed(13559): EXPERIMENTAL: Hooking native method boolean de.sky.bw.tools.NativeTools.doChecksAndLoad(android.app.Activity)
04-10 21:47:42.130: I/Xposed(13559): [SkyCast] Skull screen activation class hooked

```

Stell die Datei doch zum testen ins XDA @M66B wird sich darüber bestimmt freuen
