### ISSUE TITLE
CM-12 Lollipop 5.02 Xposed & SkyCast 1.1 native Method 06.04.2014

### ISSUE THREAD

**Issue by PanicBrothers** [mh0rst/skycast#7]
Moin,
bei mir lief alles und ich hatte ja nur die Info in der SkyGo App, dass es eine aktuallisierung gibt.
Ich bin da immer sehr vorsichtig mit, da "Restriktionen" gerne mal in Updates versteckt werden, die angeblich nur verbesserungen des Services beinhalten sollen und natürlich nur zum Wohle und der Sicherheit des Kunden gemacht werden :D :D :D
Da ich aber diese doch sehr unkreative "Hack" Sache gesehen habe, hab ich es mal aus purer Neugier installiert.

Deine Compilierte Version des Xposed vom 06.04 mit der aktuellen SkyGo App funktioniert auf dem 5.02 er Lollipop. Gefühlt würde ich sagen braucht es etwas mehr ressourcen des Handys auf aber läuft stabil mit Chromecast und anderen MiraCast Sticks.

Device ist das Sony Z3 Compact

By the way...Hast Du irgendwo einen "Donate" Button???

**Comment by mh0rst** [comment]
Hervorragend! Findest du im Log von Xposed denn auch die Ausgaben
EXPERIMENTAL: Hooking native method *irgendwas* und danach
[SkyCast] Skull screen activation class hooked ?
Wenn ja, dann verlinke ich die kompilierte Xposed-Version überall und aktualisiere die Beschreibungen.

Donate habe ich nicht, ich mache das nur zum Spaß. Wenn du dennoch willst, würde ich mich über Spenden an http://repo.xposed.info/donate freuen, ohne den guten rovo und sein Xposed wäre Android nur halb so gut.

**Comment by PanicBrothers** [comment]
Das Xposed Log liesst sich wie das Standart Log nach dem Start.
Detect die ART Runtime...Init von der Xposed Bridge und dann werden die enthaltenen Module geladen incl. Loading Modules Skycast und Loading class io.mh0rst usw.

Gibt es ein umfangreichers Logfile, dann erstelle ich eines oder wo liegt das?

Den "Donate" Link habe ich schon gut aufgefüllt, weil ohne Xposed wäre es schon nicht das was es ist !!!

**Comment by mh0rst** [comment]
Die Logeinträge erscheinen nur, wenn man Sky Go startet.

**Comment by PanicBrothers** [comment]
Grade erledigt...MiraCast Stick verbunden...SkyGo gestartet und alles lief korrekt. Unverändertes Log...nix hinzugekommen.
Xposed ggf. Experimentell Ressourcen-APIs deaktivieren??
Ist ja allerdings nur für "Theming Engines"

**Comment by mh0rst** [comment]
Merkwürdig, dann schluckt Xposed die Logs irgendwo. Ich schreib dann einfach mal eine Wikiseite, wo die Installation beschrieben ist und groß "Experimentell - Auf eigene Verantwortung" daneben (was an der Sache ja nichts ändert, Xposed auf LP ist ja eh noch im Alphastadium).
Danke auf jeden Fall fürs Ausprobieren!
