### ISSUE TITLE
Aktuelles native-xposed

### ISSUE THREAD

**Issue by fda77** [mh0rst/skycast#9]
Hallo,
könnt ihr/du bitte das Xposed mit native support auf Grundlage von Xposed 3.0 alpha4 (xposed-sdk21-arm-20150430) erstellen

**Comment by mh0rst** [comment]
Build läuft exakt in diesem Moment ;)

**Comment by fda77** [comment]
Cool dankeee :+1:

**Comment by mh0rst** [comment]
Siehe https://github.com/mh0rst/skycast/wiki/skycast-on-Lollipop
